source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OALayoutAnchor_Example', :exclusive => true do
  pod "OALayoutAnchor", :path => "../"
end

target 'OALayoutAnchor_Tests', :exclusive => true do
  pod "OALayoutAnchor", :path => "../"

  pod 'Kiwi'
end
