# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/OALayoutAnchor.xcworkspace -scheme "OALayoutAnchor-Example" -destination "platform=iOS Simulator,OS=8.1,name=iPhone 5" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick